# syntax=docker/dockerfile:1
FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
        apt-get -y --force-yes install \
        ca-certificates \
        libconfig-dev \
        wget \
        unzip \
        zip \
        automake \
        autotools-dev \
        build-essential \
        check \
        checkinstall \
        libtool \
        pkg-config \
        rsync \
        git \
        nano \
        g++ \
        cmake \
        yasm \
        sdkmanager

#        google-android-cmdline-tools-13.0-installer
#        sdkmanager

RUN yes | sdkmanager --licenses || echo "NO ERR"
RUN echo y | sdkmanager "ndk;25.1.8937393"
RUN yes | sdkmanager --licenses || echo "NO ERR"

RUN ls -al /opt/android-sdk/ || echo "NO ERR"
RUN ls -al /opt/android-sdk/ndk/ || echo "NO ERR"

# RUN wget https://github.com/openssl/openssl/releases/download/openssl-3.3.2/openssl-3.3.2.tar.gz -O /openssl-3.3.2.tar.gz
COPY openssl-3.4.1.tar.gz /openssl-3.4.1.tar.gz
RUN chmod a+r /openssl-3.4.1.tar.gz
RUN id -a;pwd
