name: filemanager
on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: list java class files
      run: |
        pwd
        find . -name '*.class'

    - name: delete java class files
      run: |
        find . -name '*.class'|xargs rm -v

    - name: build and test android version
      run: |
        ./compile_docker_all.sh || (cat compile.log; exit 1)

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: build and test linux version
      run: |
        cd 003_src_iocipher/linux_jni/c_src && ./compile_linux_c.sh || (cat compile.log; exit 1)

    - name: filemanager build
      run: |
        cd 004_example_jvm/
        pwd
        cp -v ../003_src_iocipher/linux_jni/c_src/iocipher_linux-1.0.3.jar ./iocipher_linux-1.0.3.jar
        javac -classpath ".:iocipher_linux-1.0.3.jar" FileManager.java FileDrop.java

    - name: install deps
      run: |
           sudo apt-get update
           sudo apt-get install curl wget ca-certificates
           sudo apt-get install imagemagick
           sudo apt-get install xdotool xclip
           sudo apt-get install x11-apps x11-utils
           sudo apt-get install lwm fvwm
           sudo apt-get install xvfb

    - name: show installed font packages
      run: |
           dpkg -l|grep font

    - name: install fonts
      run: |
           sudo apt-get install xfonts-utils xfonts-scalable xfonts-encodings xfonts-base xfonts-75dpi xfonts-100dpi
           sudo apt-get install fonts-noto-color-emoji
           sudo apt-get install fonts-dejavu fonts-dejavu-core fonts-freefont-ttf
           sudo apt-get install xfonts-wqy \
           xfonts-efont-unicode xfonts-efont-unicode-ib xfonts-intl-chinese xfonts-intl-chinese-big \
           xfonts-intl-asian xfonts-intl-arabic xfonts-intl-european xfonts-unifont \
            fonts-dejavu-core \
            fonts-dejavu-extra \
            fonts-droid-fallback \
            fonts-guru \
            fonts-guru-extra \
            fonts-horai-umefont \
            fonts-kacst \
            fonts-kacst-one \
            fonts-khmeros-core \
            fonts-lao \
            fonts-liberation \
            fonts-lklug-sinhala \
            fonts-lohit-guru \
            fonts-nanum \
            fonts-noto-cjk \
            fonts-opensymbol \
            fonts-roboto \
            fonts-roboto-hinted \
            fonts-sil-abyssinica \
            fonts-sil-padauk \
            fonts-stix \
            fonts-symbola \
            fonts-takao-pgothic \
            fonts-thai-tlwg \
            fonts-tibetan-machine \
            fonts-tlwg-garuda \
            fonts-tlwg-kinnari \
            fonts-tlwg-laksaman \
            fonts-tlwg-loma \
            fonts-tlwg-mono \
            fonts-tlwg-norasi \
            fonts-tlwg-purisa \
            fonts-tlwg-sawasdee \
            fonts-tlwg-typewriter \
            fonts-tlwg-typist \
            fonts-tlwg-typo \
            fonts-tlwg-umpush \
            fonts-tlwg-waree \
            fonts-unfonts-core

    - name: create runscript
      run: |
           printf '#!/bin/bash\n' > /tmp/a.sh
           printf 'xclock -digital -geometry 600x90+150+910 &\n' >> /tmp/a.sh
           printf 'cd /home/runner/work/iocipher_pack/iocipher_pack/004_example_jvm/\n' >> /tmp/a.sh
           printf './do_compile_and_run.sh vfsmanager.db "" showcase &\n' >> /tmp/a.sh
           printf 'sleep 20\n' >> /tmp/a.sh
           printf 'xwininfo -id $(xdotool getactivewindow)\n' >> /tmp/a.sh
           printf 'sleep 2\n' >> /tmp/a.sh
           printf 'pwd\n' >> /tmp/a.sh
           printf 'fvwm2 &' >> /tmp/a.sh
           printf 'sleep 20\n' >> /tmp/a.sh
           printf 'import -window root /tmp/package-screenshot-linux-deb.png\n' >> /tmp/a.sh
           cat /tmp/a.sh
           chmod a+rx /tmp/a.sh

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: startup-app
      run: |
           pwd
           ls -al
           xvfb-run --server-args="-screen 0 1920x1080x24" --auto-servernum /tmp/a.sh
           cp -av /tmp/package-screenshot-linux-deb.png package-screenshot-linux-deb.png

    - name: upload-screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-linux
        path: /tmp/package-screenshot-linux-deb.png

    - name: Upload to nightly release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        allowUpdates: true
        tag: nightly
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "package-screenshot-linux-deb.png"

