name: python_app
on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: |
        sudo apt-get update && \
        sudo DEBIAN_FRONTEND=noninteractive \
        apt-get install -y --no-install-recommends \
        git \
        fonts-freefont-otf \
        ghostscript \
        imagemagick

    - name: build and run the python example
      run: |
        cd 006_example_python/
        pwd
        ./do_compile_and_run.sh | tee out.txt

    - name: check if the C lib could be loaded OK
      run: |
        cd 006_example_python/
        cat out.txt | grep 'C library loaded'

    - name: check if test was OK
      run: |
        cd 006_example_python/
        cat out.txt | grep 'VFS: CLOSED'

    - name: make image of python console output
      run: |
        cd 006_example_python/
        date > out_with_date.txt
        echo -n 'git hash: ' >> out_with_date.txt
        git rev-parse --verify --short=8 HEAD 2>/dev/null|tr -dc '[A-Fa-f0-9]' 2>/dev/null >> out_with_date.txt
        echo "" >> out_with_date.txt
        cat out.txt >> out_with_date.txt
        cat out_with_date.txt | convert -trim -border 20 -bordercolor black +repage -background black -fill '#00cc00' -pointsize 13 TEXT:- ../python_screen.png

    - name: check image generation
      run: |
        cd 006_example_python/
        ls -al
        echo "============"
        ls -al ../

    - name: Upload to nightly release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        allowUpdates: true
        tag: nightly
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "python_screen*.png"

