name: python_app
on:
  push:
    paths-ignore:
     - 'README.md'
  pull_request:
    paths-ignore:
     - 'README.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: install deps
      run: |
        sudo apt-get update && \
        sudo DEBIAN_FRONTEND=noninteractive \
        apt-get install -y --no-install-recommends \
        fonts-freefont-otf \
        ghostscript \
        imagemagick

    - name: build and run the python example
      run: |
        cd 006_example_python/
        pwd
        ./do_compile_and_run.sh | tee out.txt

    - name: check if the C lib could be loaded OK
      run: |
        cd 006_example_python/
        cat out.txt | grep 'C library loaded'

    - name: check if test was OK
      run: |
        cd 006_example_python/
        cat out.txt | grep 'VFS: CLOSED'

    - name: make image of python console output
      run: |
        cd 006_example_python/
        cat out.txt | convert -trim +repage -background black -fill green -pointsize 18 TEXT:- ../python_screen.png

    - name: Upload to nightly release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        allowUpdates: true
        tag: nightly
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "python_screen.png"

